sge_priority option added

diff --git a/jtred b/jtred
--- a/jtred
+++ b/jtred
@@ -16,21 +16,24 @@ work="$HOME"/.jtred$$
 sleep=0.05
 outdir="$work"/o
 errdir="$work"/e
+sge_priority=-25
 
 function usage {
     cat <<-__USAGE
 	Usage:
 	  ${0##*/} [-jB btred ] [-js packet-size] [-jn job-name]
-	    [-jS sleep-interval] [-jt lrc-tmp-dir] [-jw work-dir] [-jq]
-	    { -l file-list | file... } -jb btred-options...
+            [-jS sleep-interval] [-jt lrc-tmp-dir] [-jw work-dir] [-jq]
+            [-jp sge_priority] { -l file-list | file... }
+            -jb btred-options...
 	Defaults:
-	  btred           $btred
-	  packet-size     $pack_size
-	  job-name        $job_name
-	  sleep-interval  $sleep
-	  tmp-dir         $tmp
-	  work-dir        $work
-        -jq shows only btred messages.
+          btred           $btred
+          packet-size     $pack_size
+          job-name        $job_name
+          sleep-interval  $sleep
+          tmp-dir         $tmp
+          sge_priority    $sge_priority
+          work-dir        $work
+          -jq shows only btred messages.
 	Do not enter any files nor file-lists after -jb.
 	Do not use wildcards in filelists.
 	__USAGE
@@ -58,7 +61,7 @@ quiet=0
 file_i=0 # index to file array
 while ((${#@})) ; do
     option=''
-    if [[ ! ${1:0:3} =~ ^-(j[BsnSltwbq]|l) ]] ; then
+    if [[ ! ${1:0:3} =~ ^-(j[BsnSltwbpq]|l) ]] ; then
         file[$((file_i++))]=$1 # not an option, thus a file
     elif [[ $1 == -jq ]] ; then
         quiet=1
@@ -86,6 +89,7 @@ while ((${#@})) ; do
         l) filelist=$value ;;
         t) tmp=$value ;;
         w) work=$value ;;
+        p) sge_priority=$value ;;
         b) break ;; # following options go to btred
     esac
     shift
@@ -105,6 +109,9 @@ elif (( pack_size <= 0 )) ; then
 elif [[ ! -x "$btred" ]] ; then
     echo Cannot run btred: "$btred" >&2
     exit 71
+elif ((sge_priority >= 0)) || ((sge_priority < -1023)) ; then
+    echo "Invalid priority $sge_priority (highest -1 >= int >= lowest -1023)" >&2
+    exit 74
 fi
 
 if ( [[ ! -d $outdir ]] && ! mkdir -p "$outdir" ) || [[ ! -w $outdir ]]; then
@@ -154,7 +161,7 @@ renice 10 $$ | mute
 
 # run scripts
 for script in "$tmp"/"$job_name".$$.???? ; do
-    qsub -S /bin/bash -cwd -V -p -25 -o "$outdir"/"${script##*/}".o -e "$errdir"/"${script##*/}".e "$script" | mute
+    qsub -S /bin/bash -cwd -V -p $sge_priority -o "$outdir"/"${script##*/}".o -e "$errdir"/"${script##*/}".e "$script" | mute
     sleep $sleep;
 done;
 
